"""
posture.py — Posture Classification Endpoint
=============================================

GET /posture
    Returns the latest posture prediction from the ML pipeline.
    Falls back to heuristic output when no trained model is present.

GET /posture/status
    Returns whether the XGBoost model artefact is loaded or not.
"""

from fastapi import APIRouter, Depends
from app.models.api import ApiResponse
from app.api.dependencies import get_tracker_service
from app.services.tracker import TrackerService
from pydantic import BaseModel, Field
from typing import List, Optional

router = APIRouter(tags=["Posture ML"])


class PostureResponse(BaseModel):
    """Posture classification result."""
    posture: Optional[str]               = Field(None, description="Predicted posture class")
    confidence: Optional[float]          = Field(None, description="Prediction confidence [0,1]")
    recommendations: Optional[List[str]] = Field(None, description="Actionable ergonomic advice")
    source: Optional[str]                = Field(None, description="'model' | 'heuristic' | None")
    face_detected: bool                  = Field(...,  description="Whether a face is currently tracked")


class ModelStatusResponse(BaseModel):
    """Status of the posture ML model artefact."""
    model_loaded: bool
    model_path: str
    scaler_loaded: bool
    source: str


@router.get(
    "/posture",
    response_model=ApiResponse[PostureResponse],
    summary="Get latest posture classification",
    description=(
        "Returns the posture prediction generated by the ML pipeline on the last "
        "camera frame.  If no trained model artefact is present the heuristic "
        "rule-based classifier is used and `source` will be `'heuristic'`."
    ),
)
async def get_posture(
    tracker: TrackerService = Depends(get_tracker_service),
) -> ApiResponse[PostureResponse]:
    state = tracker.get_latest_state()

    from app.models.tracker import TrackerStatus
    face_detected = state.status == TrackerStatus.RUNNING

    data = PostureResponse(
        posture=state.posture,
        confidence=state.posture_confidence,
        recommendations=state.posture_recommendations,
        source=state.posture_source,
        face_detected=face_detected,
    )

    return ApiResponse[PostureResponse](
        success=True,
        data=data,
        message="Posture retrieved." if face_detected else "No face detected.",
    )


@router.get(
    "/posture/status",
    response_model=ApiResponse[ModelStatusResponse],
    summary="Posture model artefact status",
    description="Check whether the trained XGBoost model is loaded.",
)
async def get_posture_status() -> ApiResponse[ModelStatusResponse]:
    try:
        from app.ml.inference.predict import get_model_status
        info = get_model_status()
    except Exception as exc:
        info = {
            "model_loaded": False,
            "model_path":   "unknown",
            "scaler_loaded": False,
            "source":       "unavailable",
        }

    return ApiResponse[ModelStatusResponse](
        success=True,
        data=ModelStatusResponse(**info),
        message="Model status retrieved.",
    )
